CREATE TABLE   COMPANY_MAILER_USER  
   (ID  id(50), 
	 NAME  VARCHAR (400), 
	 EMAIL  VARCHAR (400), 
	 PASSWORD  VARCHAR (400), 
	 GENDER  VARCHAR (400), 
	 DOB  DATE, 
	 ADDRESSLINE  VARCHAR (400), 
	 CITY  VARCHAR (400), 
	 STATE  VARCHAR (400), 
	 COUNTRY  VARCHAR (400), 
	 CONTACT  VARCHAR (400), 
	 REGISTEREDDATE  DATE, 
	 AUTHORIZED  VARCHAR (400), 
	 CONSTRAINT  COMPANY_MAILER_USER_PK  PRIMARY KEY ( ID )
   );
   
CREATE TABLE   COMPANY_MAILER_MESSAGE  
   (ID  id(50), 
	 SENDER  VARCHAR (400), 
	 RECEIVER  VARCHAR (400), 
	 SUBJECT  VARCHAR (400), 
	 MESSAGE  VARCHAR (400), 
	 TRASH  VARCHAR (400), 
	 MESSAGEDATE  DATE, 
	 CONSTRAINT  COMPANY_MAILER_MESSAGE_PK  PRIMARY KEY ( ID )
   );